### ITCS 4122: Visual Analytics Project
**This notebook is an initial exploration of our chosen dataset**

The data was accessed from [Charlotte's Data Portal](https://data.charlottenc.gov/datasets/charlotte::housing-demand-and-availability-by-income/about) and its source is the [2018 American Community Survey (ACS)](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/ACS2014_2018_PUMS_README.pdf). 

The City of Charlotte summarized lots of the data from the ACS and provided some further documentation [here](https://www.census.gov/programs-surveys/acs/microdata/documentation.2018.html).

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#https://gis.charlottenc.gov/arcgis/rest/services/ODP/HousingDemandandAvailabilityByIncome/MapServer/1
pd.set_option('display.max_columns', None)
df = pd.read_csv('data_sets/Housing_Demand_and_Availability_by_Income.csv')

In [3]:
df.head(5)

OBJECTID RT       SERIALNO  DIVISION  PUMA  REGION  ST   ADJHSG   ADJINC  \
0         1  H  2018HU0001431         5  3102       3  37  1000000  1013097   
1         2  H  2018HU0001750         5  3104       3  37  1000000  1013097   
2         3  H  2018HU0005740         5  3105       3  37  1000000  1013097   
3         4  H  2018HU0005916         5  3101       3  37  1000000  1013097   
4         5  H  2018HU0006498         5  3105       3  37  1000000  1013097   

   WGTP  NP  TYPE  ACCESS  ACR  AGS  BATH  BDSP  BLD  BROADBND  COMPOTHX  \
0   204   5     1     1.0  1.0  NaN     1     3    2       1.0       2.0   
1   113   1     1     1.0  NaN  NaN     1     2    6       1.0       2.0   
2    83   0     1     NaN  NaN  NaN     1     2    5       NaN       NaN   
3    90   2     1     1.0  1.0  NaN     1     3    2       1.0       2.0   
4    63   4     1     1.0  NaN  NaN     1     2    7       1.0       2.0   

   CONP  DIALUP  ELEFP   ELEP   FS  FULFP  FULP  GASFP  GASP  HFL  HISPEED  \
0   NaN     2.0    3.0  100.0  1.0    2.0   NaN    4.0  50.0  3.0      1.0   
1   NaN     2.0    3.0  120.0  2.0    2.0   NaN    3.0   NaN  3.0      1.0   
2   NaN     NaN    NaN    NaN  NaN    NaN   NaN    NaN   NaN  NaN      NaN   
3   NaN     2.0    3.0  170.0  2.0    2.0   NaN    4.0  70.0  1.0      2.0   
4   NaN     2.0    3.0   80.0  2.0    2.0   NaN    3.0   NaN  3.0      1.0   

   HOTWAT  INSP  LAPTOP  MHP  MRGI  MRGP  MRGT  MRGX  OTHSVCEX  REFR  RMSP  \
0       9   NaN     1.0  NaN   NaN   NaN   NaN   NaN       2.0     1     5   
1       9   NaN     1.0  NaN   NaN   NaN   NaN   NaN       2.0     1     7   
2       9   NaN     NaN  NaN   NaN   NaN   NaN   NaN       NaN     1     4   
3       9   NaN     2.0  NaN   NaN   NaN   NaN   NaN       2.0     1     5   
4       9   NaN     1.0  NaN   NaN   NaN   NaN   NaN       2.0     1     6   

   RNTM    RNTP  RWAT  RWATPR  SATELLITE  SINK  SMARTPHONE  SMP  STOV  TABLET  \
0   2.0   800.0     1       9        2.0     1         1.0  NaN     1     1.0   
1   2.0  1100.0     1       9        2.0     1         1.0  NaN     1     1.0   
2   2.0   450.0     1       9        NaN     1         NaN  NaN     1     NaN   
3   2.0   600.0     1       9        2.0     1         1.0  NaN     1     2.0   
4   2.0   800.0     1       9        2.0     1         1.0  NaN     1     1.0   

   TEL  TEN  VACS  VALP  VEH  WATFP   WATP  YBL  FES    FINCP  FPARC   GRNTP  \
0  1.0  3.0   NaN   NaN  1.0    3.0  750.0    5  7.0  18000.0    3.0  1013.0   
1  1.0  3.0   NaN   NaN  1.0    3.0   40.0    6  NaN      NaN    NaN  1223.0   
2  NaN  NaN   1.0   NaN  NaN    NaN    NaN   19  NaN      NaN    NaN     NaN   
3  1.0  3.0   NaN   NaN  2.0    3.0  520.0    5  1.0  56600.0    4.0   883.0   
4  1.0  3.0   NaN   NaN  2.0    3.0  380.0    6  1.0  59400.0    2.0   912.0   

   GRPIP  HHL  HHLANP  HHT    HINCP  HUGCL  HUPAC  HUPAOC  HUPARC  KIT  LNGI  \
0   68.0  1.0  9500.0  3.0  18000.0    0.0    3.0     3.0     3.0    1   1.0   
1   20.0  1.0  9500.0  4.0  72000.0    0.0    4.0     4.0     4.0    1   1.0   
2    NaN  NaN     NaN  NaN      NaN    NaN    NaN     NaN     NaN    1   NaN   
3   19.0  1.0  9500.0  1.0  56600.0    0.0    4.0     4.0     4.0    1   1.0   
4   18.0  1.0  9500.0  1.0  59400.0    0.0    2.0     2.0     2.0    1   1.0   

   MULTG   MV  NOC  NPF  NPP   NR  NRC  OCPIP  PARTNER  PLM  PLMPRP  PSF  R18  \
0    1.0  4.0  3.0  5.0  0.0  0.0  3.0    NaN      0.0    1       9  0.0  1.0   
1    1.0  1.0  0.0  NaN  0.0  0.0  0.0    NaN      0.0    1       9  0.0  0.0   
2    NaN  NaN  NaN  NaN  NaN  NaN  NaN    NaN      NaN    1       9  NaN  NaN   
3    1.0  4.0  0.0  2.0  0.0  0.0  0.0    NaN      0.0    1       9  0.0  0.0   
4    1.0  1.0  2.0  4.0  0.0  0.0  2.0    NaN      0.0    1       9  0.0  1.0   

   R60  R65  RESMODE  SMOCP  SMX  SRNT  SSMC  SVAL  TAXAMT  WIF  WKEXREL  \
0  1.0  1.0        2    NaN  NaN     1   0.0     0     NaN  1.0     13.0   
1  0.0  0.0        3    NaN  NaN     1   0.0 

In [4]:
df.shape

(1754, 241)

In [5]:
df.isna().any()

OBJECTID        False
RT              False
SERIALNO        False
DIVISION        False
PUMA            False
                ...  
AMI              True
AFF_OCC          True
AFF_VACS         True
COST_BURDALL     True
YEAR            False
Length: 241, dtype: bool

[Detailed Code List / Data Dictionary](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2014-2018.pdf) 

Charlotte added a handful of [other metrics](https://ago-item-storage.s3.us-east-1.amazonaws.com/b9cb7f48017b4dd882bd8b75b0b736f9/Housing_Affordability_and_Availability.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEAgaCXVzLWVhc3QtMSJIMEYCIQDty8bRWOcapO0u4ej7UkmuZih9gl%2F5pZlu9srrFdZvVAIhAIHd9k2BD02I7wQL5Jt8BD1aVHr05VM%2BAs8LJ%2FqVtZErKvoDCGAQABoMNjA0NzU4MTAyNjY1IgzGShvWkz106KqlAFQq1wNJqomaCtMKCbJxgEkRTKXXhDUs3EspDDV4tMzftBKj1fHEwtWzrKpMO1NbnzQHSHAZkRPnwHPQ77NdXpJXVzs1MggsCvGMU6w2gF36yiFoAhDUp%2B0G4dMWG86H%2FEKS2jI4Ya9tMqNROIDLa7A2TQPTwOkPJzWbSnHuk8RIrFiF2mv2WMVNwkyRGmCYx7hmkVlAx6AWNiodu6Vq1xEHH6GmGDUxkd5UX6gJ%2FVxsv8cn6J3jkNIQiAI62Q2kIwTDmhOTWkOLxy1H3cve3WC845frjWL9cl0AQy1JU%2FRYA%2FmBRKlpA4MXkZh1xhK5GD50n7SC2JGvbUgVsB%2Fwpueusw2QrXdsmvoLNVXRvqjCQ7OA41ooHlzmnz09IppHOCRQfPua5WmEwWtXh3RlaL30xDM53AR5mobmUdOMK8VDbMHn3o8HXEmRuInVgUuYHbkLIOacjET6H8vG3cZ7unwkfP8NE%2Ftb9KQnbP9uzxsbC99%2BPf2FCsOR2DkD5Wpb3LfGnho4FT%2FiTurEhV4QLsCzQ%2BHzHDbME4t2xbKVA5O9bEs3toICBGhhbUfjNV9ptlt6JMee54DU7R8TcstgJEsDU5UF8w28jR2MDGbyxn1XsVJwC8MqSYriw80wzPrTkAY6pAGl6gg4GeXwfIqo3lAwc0WcOr7gQ%2BFSOP%2Fa%2Fwymx6JzKuYzKsK5vsj0vZs%2FIyI5dXaK2zWhK6ovV3pdOKAqpOLXeLksyBnrgY26z4rVQp8VARkcHN%2FJ3bWKEmXaD0OxVMUMGddLCp%2Fe%2Fr%2FBoVw1ZjFXB8Nl%2B7EKKfq6ZJkC3r8ckMOBQkFibdOKUkvfPcgvgcf6STxmRHs1BE48NMkamIHKpAwMvQ%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220222T161107Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAYZTTEKKEULNGVXP4%2F20220222%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=b3bc63f4d7cca14cbf069efed8442c52c181f87dd8e1ced7ae67c86bad7763f7) based on the given data. Those metrics are as follows:
- WGTP_CLT: Housing Unit Weight for City of Charlotte
- AMI: Area median income for the household
- AFF_OCC: The affordability of the rental housing unit
- AFF_VACS: The affordability level of the vancant rental housing unit.
- COST_BURDALL: Cost-burdened status of household
- YEAR: Year of the ACS PUMS data

[Replicate Weights Reference](https://usa.ipums.org/usa/repwt.shtml): "Replicate weights allow a single sample to simulate multiple samples, thus generating more informed standard error estimates that mimic the theoretical basis of standard errors while retaining all information about the complex sample design."

### Data Dictionary
A machine readable data dictionary is provided. I will create a couple functions to assist in looking up the semantics of the features as needed.

In [6]:
data_dict = pd.read_csv('data_sets/data_dictionary.csv')
#sort to optimize lookup performance
data_dict = data_dict.sort_index() 
#NOTE: the following features are not in the Dictionary since they were added by the city of Charlotte.
#      ['WGTP_CLT', 'AMI', 'AFF_OCC', 'AFF_VACS', 'COST_BURDALL', 'YEAR']

In [7]:
'''
Look up the semantics of a feature name

    Parameters:
        feat (str): name of column/feature
    Returns:
        data description (str)
'''
def lookup_feat(feat):
    try:
        desc = data_dict.loc['NAME', feat]['C'][0]
    except: 
        return '***LOOK UP FAILED***'
    else:
        return desc

'''
Look up the semantics of a specified value of a feature

    Parameters:
        feat (str): name of column/feature
        value (str): particular value within column
    Returns:
        data description (str)
'''
def lookup_value(feat, value):
    try:
        subset = data_dict.loc['VAL', feat]
        desc = subset[subset['C'] == value]['Record Type'][0]
    except:
        return '***LOOK UP FAILED***'
    else:
        return desc
    
'''
Look up all values and their semantics of a feature

    Parameters:
        feat (str): name of column/feature
    Returns:
        data description (pandas.DataFrame)
'''
def lookup_values(feat):
    try:
        subset = data_dict.loc['VAL', feat]
        desc = subset[['C', 'Record Type']]
        desc = desc.reset_index().drop(columns = ['level_0', 'level_1']).rename(columns = {'C':'Value'})
    except:
        return '***LOOK UP FAILED***'
    else:
        return desc

### Data Cleaning
Manually exploring features to see what will be useful.

In [8]:
#check columns that only contain a single unique value
redudant = []
for col in df.columns:
    if len(df[col].unique()) == 1:
          redudant.append(col)

In [9]:
#see the semantics of the redundant columns
for i in redudant:
    print(i, ':', lookup_feat(i))

RT : Record Type
DIVISION : Division code based on 2010 Census definitions
REGION : Region code based on 2010 Census definitions
ST : State code based on 2010 Census definitions
ADJHSG : Adjustment factor for housing dollar amounts (6 implied decimal places)
ADJINC : Adjustment factor for income and earnings dollar amounts (6 implied decimal places)
TYPE : Type of unit
CONP : Condo fee (monthly amount, use ADJHSG to adjust CONP to constant dollars)
HOTWAT : Water heater (Puerto Rico only)
INSP : Fire/hazard/flood insurance (yearly amount, use ADJHSG to adjust INSP to constant dollars)
MHP : Mobile home costs (yearly amount, use ADJHSG to adjust MHP to constant dollars)
MRGI : First mortgage payment includes fire/hazard/flood insurance
MRGP : First mortgage payment (monthly amount, use ADJHSG to adjust MRGP to constant dollars)
MRGT : First mortgage payment includes real estate taxes
MRGX : First mortgage status
RWATPR : Running water
SMP : Total payment on all second and junior mortgag

In [10]:
df[redudant].head()

RT  DIVISION  REGION  ST   ADJHSG   ADJINC  TYPE  CONP  HOTWAT  INSP  MHP  \
0  H         5       3  37  1000000  1013097     1   NaN       9   NaN  NaN   
1  H         5       3  37  1000000  1013097     1   NaN       9   NaN  NaN   
2  H         5       3  37  1000000  1013097     1   NaN       9   NaN  NaN   
3  H         5       3  37  1000000  1013097     1   NaN       9   NaN  NaN   
4  H         5       3  37  1000000  1013097     1   NaN       9   NaN  NaN   

   MRGI  MRGP  MRGT  MRGX  RWATPR  SMP  OCPIP  PLMPRP  SMOCP  SMX  TAXAMT  \
0   NaN   NaN   NaN   NaN       9  NaN    NaN       9    NaN  NaN     NaN   
1   NaN   NaN   NaN   NaN       9  NaN    NaN       9    NaN  NaN     NaN   
2   NaN   NaN   NaN   NaN       9  NaN    NaN       9    NaN  NaN     NaN   
3   NaN   NaN   NaN   NaN       9  NaN    NaN       9    NaN  NaN     NaN   
4   NaN   NaN   NaN   NaN       9  NaN    NaN       9    NaN  NaN     NaN   

   FCONP  FHOTWATP  FINSP  FMHP  FMRGIP  FMRGP  FMRGTP  FMRGXP  FPLMPRP  \
0      0         0      0     0       0      0       0       0        0   
1      0         0      0     0       0      0       0       0        0   
2      0         0      0     0       0      0       0       0        0   
3      0         0      0     0       0      0       0       0        0   
4      0         0      0     0       0      0       0       0        0   

   FRWATPRP  FSMOCP  FSMP  FSMXHP  FSMXSP  FTAXP  YEAR  
0         0       0     0       0       0      0  2018  
1         0       0     0       0       0      0  2018  
2         0       0     0       0       0      0  2018  
3         0       0     0       0       0      0  2018  
4         0       0     0       0       0      0  2018

**Note:** A lot of the redudant features are regional data. Remember, all of this data comes from a national survey and our specific subset is specific to Charlotte. Beyond that, the rest of the data is empty.

In [11]:
#drop redudant features, new dataframe
df_cleaned = df.drop(columns = redudant)

In [12]:
df_cleaned.shape

(1754, 203)

In [13]:
#overview semantics of remaining columns
for col in df_cleaned.columns:
    print(col, ' ', lookup_feat(col))

OBJECTID   ***LOOK UP FAILED***
SERIALNO   Housing unit/GQ person serial number
PUMA   Public use microdata area code (PUMA) based on 2010 Census definition (areas with population of 100,000 or more, use with ST for unique code)
WGTP   Housing Unit Weight
NP   Number of persons associated with this housing record
ACCESS   Access to the Internet
ACR   Lot size
AGS   Sales of agriculture products (yearly sales, no adjustment factor is applied)
BATH   Bathtub or shower
BDSP   Number of bedrooms
BLD   Units in structure
BROADBND   Cellular data plan for a smartphone or other mobile device
COMPOTHX   Other computer equipment
DIALUP   Dial-up service
ELEFP   Electricity cost flag variable
ELEP   Electricity cost (monthly cost, use ADJHSG to adjust ELEP to constant dollars)
FS   Yearly food stamp/Supplemental Nutrition Assistance Program (SNAP) recipiency
FULFP   Fuel cost flag variable
FULP   Fuel cost (yearly cost for fuels other than gas and electricity, use ADJHSG to adjust FULP to consta

### Thoughts so far
There is tons of valuable data within the columns and potential for tons of data exploration and insight. However with all this data, manual inspection can be a bit more tedious. After lots of referencing of ACS PUMS documentation and a bit of exploration of distributions of some features, here are my thoughts:

I do not fully understand the **weight** features (Ex: WGTP*) . I assume they are there to assist in some type of regression analysis or other modeling. But I don't think they are necessary for visualizations. I think I will separate them for now. [Reference](https://www.census.gov/content/dam/Census/library/publications/2020/acs/acs_pums_handbook_2020_ch04.pdf)

The **flag variables** are interesting as well. Some features take on a quantitative value (such as water cost) but also have a categorical flag variable to represent when it is either not applicable or zero. I need to explore if its worth trying to combine these into a single feature or just drop altogether.

There is also **allocation flag** variables. From what I can tell, these flags are raised when the value for their corresponding features are inferred of imputed in some way. I *think* these really won't be needed for modeling or visuals. They probably are meant to reflect validity of the data. [Reference](https://www.census.gov/programs-surveys/acs/methodology/sample-size-and-data-quality/item-allocation-rates-definitions.html)

I'm going to go ahead and drop the unique identifiers **(OBJECTID, SERIALNO)** as they won't be needed for our purposes.

The affordability data provided by charlotte can be treated as "target values" for modeling and correlations.  

In [14]:
df_cleaned = df_cleaned.drop(columns = ['OBJECTID', 'SERIALNO'])

In [15]:
#drop allocation features by parsing their definition
allo_flags = []
for col in df_cleaned.columns:
    desc = lookup_feat(col)
    if 'allocation' in desc.lower():
        allo_flags.append(col)

In [16]:
df_cleaned = df_cleaned.drop(columns = allo_flags)

In [17]:
df_cleaned.shape

(1754, 161)

**TODO**: figure out what to do with all the replicate weights / how to properly use them

In [18]:
#get all weight columns
weights = []
for i in df_cleaned.columns:
    if "WGTP" in i:
        weights.append(i)

In [19]:
#separate weights into their own column
df_weights = df_cleaned[weights]
df_cleaned = df_cleaned.drop(columns = weights)

In [20]:
df_cleaned.shape

(1754, 79)

In [21]:
#get nulls by ROW
high_nulls_df = df_cleaned.loc[df_cleaned.isnull().sum(axis = 1) > 40]

In [22]:
#Are rows with more nulls vacant?
high_nulls_df.VACS.value_counts()

1.0    82
7.0    57
5.0    22
2.0    22
3.0    20
4.0     9
Name: VACS, dtype: int64

In [23]:
high_nulls_df.VACS.value_counts().sum()

212

In [24]:
high_nulls_df.shape

(212, 79)

**NOTE:** As we can see, all of the rows with high amounts of nulls are all vacant, which makes sense. Will separate vacant rows into their own DF

In [25]:
lookup_values('VACS')

Value                               Record Type
0     b                         N/A (GQ/occupied)
1     1                                  For rent
2     2                      Rented, not occupied
3     3                             For sale only
4     4                        Sold, not occupied
5     5  For seasonal/recreational/occasional use
6     6                       For migrant workers
7     7                              Other vacant

In [26]:
#Separate vacant households into their own df
df_vacant = df_cleaned.loc[~df_cleaned.VACS.isna()]
df_cleaned = df_cleaned.loc[df_cleaned.VACS.isna()]

In [27]:
df_cleaned.shape

(1542, 79)

In [28]:
#get nulls by COLUMN
nulls = df_cleaned.isnull().sum(axis = 0)
for i in range(len(nulls)):
    print(df_cleaned.columns[i], '\t', nulls[i])

PUMA 	 0
NP 	 0
ACCESS 	 0
ACR 	 1016
AGS 	 1500
BATH 	 0
BDSP 	 0
BLD 	 0
BROADBND 	 206
COMPOTHX 	 0
DIALUP 	 206
ELEFP 	 0
ELEP 	 97
FS 	 0
FULFP 	 0
FULP 	 1520
GASFP 	 0
GASP 	 1094
HFL 	 0
HISPEED 	 206
LAPTOP 	 0
OTHSVCEX 	 206
REFR 	 0
RMSP 	 0
RNTM 	 32
RNTP 	 32
RWAT 	 0
SATELLITE 	 206
SINK 	 0
SMARTPHONE 	 0
STOV 	 0
TABLET 	 0
TEL 	 0
TEN 	 0
VACS 	 1542
VALP 	 1542
VEH 	 0
WATFP 	 0
WATP 	 556
YBL 	 0
FES 	 843
FINCP 	 836
FPARC 	 836
GRNTP 	 32
GRPIP 	 68
HHL 	 0
HHLANP 	 0
HHT 	 0
HINCP 	 0
HUGCL 	 0
HUPAC 	 0
HUPAOC 	 0
HUPARC 	 0
KIT 	 0
LNGI 	 0
MULTG 	 0
MV 	 0
NOC 	 0
NPF 	 836
NPP 	 0
NR 	 0
NRC 	 0
PARTNER 	 0
PLM 	 0
PSF 	 0
R18 	 0
R60 	 0
R65 	 0
RESMODE 	 0
SRNT 	 0
SSMC 	 0
SVAL 	 0
WIF 	 836
WKEXREL 	 836
WORKSTAT 	 843
AMI 	 0
AFF_OCC 	 4
AFF_VACS 	 1542
COST_BURDALL 	 32


**NOTE:** After referencing the Data Dictionary, It looks like the nulls don't necessarily mean the data is missing but more or less that the metric is not applicable to the given metric. I will fill the nulls with a value of 0 to represent not applicable.

In [29]:
#drop redudant columns again
#check columns that only contain a single unique value
to_drop = []
rows = len(df_cleaned)
for col in df_cleaned.columns:
    #drop redudant columns
    if len(df_cleaned[col].unique()) == 1:
          to_drop.append(col)
    #drop columns with many (greater than 500) nulls
    if df_cleaned[col].isna().sum() > 500:
        to_drop.append(col)
df_cleaned = df_cleaned.drop(columns = to_drop)
df_cleaned.shape

(1542, 63)

In [30]:
df_cleaned.PUMA.value_counts()

3101    334
3105    254
3102    206
3103    184
3104    157
3106    147
3108    145
3107    115
Name: PUMA, dtype: int64

**NOTE:** PUMA (Public Use Microdata Area) attribute contains codes that correspond to an geographic area. This dataset contains 8 Different codes that are all within North Carolina.

- 3101 : Charlotte City (Central) 
- 3102 : Charlotte City (Northwest) 
- 3103 : Charlotte City (Northeast) 
- 3104 : Charlotte City (South) 
- 3105 : Charlotte City (Southwest)
- 3106 : Mecklenburg County (North)--Huntersville, Cornelius & Davidson Towns 
- 3107 : Mecklenburg County (East)--Mint Hill & Matthews (North) Towns 
- 3108 : Mecklenburg County (South)--Matthews Town (South) 

In [31]:
#create python dictionary for PUMA codes
PUMA_codes = {
    3101 : "Charlotte City (Central)", 
    3102 : "Charlotte City (Northwest)", 
    3103 : "Charlotte City (Northeast)",
    3104 : "Charlotte City (South)",
    3105 : "Charlotte City (Southwest)", 
    3106 : "Mecklenburg County (North)--Huntersville, Cornelius & Davidson Towns",
    3107 : "Mecklenburg County (East)--Mint Hill & Matthews (North) Towns",
    3108 : "Mecklenburg County (South)--Matthews Town (South)"
             }

In [32]:
PUMA_codes[3101]

'Charlotte City (Central)'

In [33]:
df_cleaned = df_cleaned.fillna(df_cleaned.mean().round())

### Cleaning Recap
- Redudant (columns of only a single value) were dropped
- Flag Columns were dropped
- Weight columns were dropped (may need to revisit for modeling)
- Vacant households were dropped 
- Unique identifiers were dropped
- Nulls were filled with average

I believe that is all that is necessary for initial cleaning. Further rearrangement/processing will be needed depending on model implementation.

In [34]:
#export cleaned csv
df_cleaned.to_csv('data_sets/df_cleaned.csv')

### Proposal Outline
Our proposal can consist of
- Motivation
    - Why we are focusing on local data / Why exploring housing in particular
- Data Introduction
    - Talk about data source (Charlotte Data Portal and ACS PUMS)
    - Talk about the type of data (tabular)
    - Introduce features and size 
    - Discuss initial cleaning done / thought process of initial cleaning
- Planned methods for visualizations / visual encoding
    - UI Sketch
- Plans for modeling
    - regression/classification
    